<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PcBuilder.ScraperWorker-a479ff5d-2ebc-4a93-905d-e74558c1efbf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.14" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PcBuilder.Contracts\PcBuilder.Contracts.csproj" />
    <ProjectReference Include="..\PcBuilder.SharedKernel\PcBuilder.SharedKernel.csproj" />
    <ProjectReference Include="..\PcBuilder.Persistence\PcBuilder.Persistence.csproj" />
    <ProjectReference Include="..\Modules\Scraping\Scraping.Infrastructure\Scraping.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Scraping\Scraping.Application\Scraping.Application.csproj" />
    <ProjectReference Include="..\Modules\Components\Components.Domain\Components.Domain.csproj" />
  </ItemGroup>
</Project>
