// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcBuilder.Persistence.Data;

#nullable disable

namespace PcBuilder.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CommentBanUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostBanUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Components.Domain.Entities.Cpu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("BasicFrequency")
                        .HasColumnType("float");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Cache")
                        .HasColumnType("int");

                    b.Property<string>("Complectation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("DimmType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxFrequency")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Tdp")
                        .HasColumnType("int");

                    b.Property<string>("Techprocess")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Threads")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuCooler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AirflowCfm")
                        .HasColumnType("float");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FanCount")
                        .HasColumnType("int");

                    b.Property<double?>("FanSize")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<int?>("Lifespan")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPowerDissipation")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MinSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("NoiseLevelDb")
                        .HasColumnType("float");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerConnector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpeedControl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Voltage")
                        .HasColumnType("int");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CpuCoolers", t =>
                        {
                            t.HasCheckConstraint("CHK_CpuCooler_Type", "Type IN ('Air', 'Water')");
                        });
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuCoolerSocket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CpuCoolerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CpuCoolerId");

                    b.ToTable("CpuCoolerSockets");
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuPowerConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pins")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("CpuPowerConnectors");
                });

            modelBuilder.Entity("Components.Domain.Entities.Fan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AirflowCfm")
                        .HasColumnType("float");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Connector")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MinSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("ModuleCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double?>("NoiseLevelDb")
                        .HasColumnType("float");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SizeHeight")
                        .HasColumnType("float");

                    b.Property<double?>("SizeLength")
                        .HasColumnType("float");

                    b.Property<double?>("SizeWidth")
                        .HasColumnType("float");

                    b.Property<string>("SpeedControl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Voltage")
                        .HasColumnType("int");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Fans");
                });

            modelBuilder.Entity("Components.Domain.Entities.Gpu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CudaCores")
                        .HasColumnType("int");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GpuManufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GpuModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("Memory")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryBus")
                        .HasColumnType("int");

                    b.Property<int?>("MemorySpeed")
                        .HasColumnType("int");

                    b.Property<string>("MemoryType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<int?>("PcleLane")
                        .HasColumnType("int");

                    b.Property<double?>("PcleVersion")
                        .HasColumnType("float");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PsuReccomended")
                        .HasColumnType("int");

                    b.Property<double?>("SizeHeight")
                        .HasColumnType("float");

                    b.Property<double?>("SizeLength")
                        .HasColumnType("float");

                    b.Property<double?>("SizeWidth")
                        .HasColumnType("float");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("Components.Domain.Entities.GpuPowerConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GpuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pins")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GpuId");

                    b.ToTable("GpuPowerConnectors");
                });

            modelBuilder.Entity("Components.Domain.Entities.Hdd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Cache")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interface")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NoiceDb")
                        .HasColumnType("int");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Speed")
                        .HasColumnType("int");

                    b.Property<int?>("SpindleSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.Property<string>("WritingTechnology")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hdds");
                });

            modelBuilder.Entity("Components.Domain.Entities.InnerPort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("InnerPorts");
                });

            modelBuilder.Entity("Components.Domain.Entities.M2Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Lane")
                        .HasColumnType("int");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Version")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("M2Slots");
                });

            modelBuilder.Entity("Components.Domain.Entities.Motherboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bluetooth")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DimmCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("DimmFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("DimmSlots")
                        .HasColumnType("int");

                    b.Property<string>("DimmType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ethernet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FanQuantity")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<int?>("PcleX1Quantity")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PowerMotherboard")
                        .HasColumnType("int");

                    b.Property<int?>("Sata3Count")
                        .HasColumnType("int");

                    b.Property<string>("SizeDimentions")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoPorts")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.Property<string>("Wifi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ExpansionSlotQuant")
                        .HasColumnType("int");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDustFilters")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHeadphones")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMicrophone")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxCpuCoolerHeight")
                        .HasColumnType("float");

                    b.Property<double?>("MaxGpuLength")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PsuWattage")
                        .HasColumnType("int");

                    b.Property<string>("SizeDimentions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SizeStandard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Slot25Quant")
                        .HasColumnType("int");

                    b.Property<int?>("Slot35Quant")
                        .HasColumnType("int");

                    b.Property<int?>("Slot525Quant")
                        .HasColumnType("int");

                    b.Property<string>("Usb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PcCases");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCaseFanLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FanSize")
                        .HasColumnType("int");

                    b.Property<int>("MaxFans")
                        .HasColumnType("int");

                    b.Property<Guid>("PcCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PcCaseId");

                    b.ToTable("PcCaseFanLocations");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCaseFormFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PcCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PcCaseId");

                    b.ToTable("PcCaseFormFactors");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcleSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Lane")
                        .HasColumnType("int");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Version")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("PcleSlots");
                });

            modelBuilder.Entity("Components.Domain.Entities.PowerSupply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("EfficiencyPercent")
                        .HasColumnType("float");

                    b.Property<string>("EfficiencyStandart")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FddCount")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasApcf")
                        .HasColumnType("bit");

                    b.Property<int?>("InputMaxVoltage")
                        .HasColumnType("int");

                    b.Property<int?>("InputMinVoltage")
                        .HasColumnType("int");

                    b.Property<int?>("MolexCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("NoiseLevelMaxDb")
                        .HasColumnType("float");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SataCount")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplies");
                });

            modelBuilder.Entity("Components.Domain.Entities.PowerSupplyPowerConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AdditionalPins")
                        .HasColumnType("int");

                    b.Property<int>("Pins")
                        .HasColumnType("int");

                    b.Property<Guid>("PowerSupplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PowerSupplyId");

                    b.ToTable("PowerSupplyPowerConnectors");
                });

            modelBuilder.Entity("Components.Domain.Entities.ProductOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComponentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductOfferUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ComponentId", "ComponentType");

                    b.ToTable("ProductOffers");
                });

            modelBuilder.Entity("Components.Domain.Entities.Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bufferization")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("Ecc")
                        .HasColumnType("bit");

                    b.Property<bool>("Expo")
                        .HasColumnType("bit");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int?>("ModuleQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timings")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Voltage")
                        .HasColumnType("float");

                    b.Property<int?>("Wattage")
                        .HasColumnType("int");

                    b.Property<bool>("Xmp")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("Components.Domain.Entities.RearPort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("RearPorts");
                });

            modelBuilder.Entity("Components.Domain.Entities.Ssd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageLifeTime")
                        .HasColumnType("float");

                    b.Property<decimal?>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("FactoryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Interface")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsTrimmSupported")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxReadSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MaxWriteSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NandType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OffersCount")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RandomReadSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("RandomWriteSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<int?>("WritingRecource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ssds");
                });

            modelBuilder.Entity("Components.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<Guid?>("CpuCoolerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CpuCoolerOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CpuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CpuOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("GpuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GpuOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MotherboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MotherboardOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("PcCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PcCaseOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PowerSupplyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PowerSupplyOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CpuCoolerId");

                    b.HasIndex("CpuCoolerOfferId");

                    b.HasIndex("CpuId");

                    b.HasIndex("CpuOfferId");

                    b.HasIndex("GpuId");

                    b.HasIndex("GpuOfferId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("MotherboardOfferId");

                    b.HasIndex("PcCaseId");

                    b.HasIndex("PcCaseOfferId");

                    b.HasIndex("PowerSupplyId");

                    b.HasIndex("PowerSupplyOfferId");

                    b.HasIndex("UserId");

                    b.ToTable("PcBuilds");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Fan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PcBuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FanId");

                    b.HasIndex("PcBuildId");

                    b.HasIndex("ProductOfferId");

                    b.ToTable("PcBuild_Fan", (string)null);
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Hdd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HddId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PcBuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HddId");

                    b.HasIndex("PcBuildId");

                    b.HasIndex("ProductOfferId");

                    b.ToTable("PcBuild_Hdd", (string)null);
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PcBuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PcBuildId");

                    b.HasIndex("ProductOfferId");

                    b.HasIndex("RamId");

                    b.ToTable("PcBuild_Ram", (string)null);
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Ssd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PcBuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SsdId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PcBuildId");

                    b.HasIndex("ProductOfferId");

                    b.HasIndex("SsdId");

                    b.ToTable("PcBuild_Ssd", (string)null);
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PcBuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PcBuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuCooler", b =>
                {
                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "RadiatorMaterial", b1 =>
                        {
                            b1.Property<Guid>("CpuCoolerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RadiatorMaterial_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RadiatorMaterial_Uk");

                            b1.HasKey("CpuCoolerId");

                            b1.ToTable("CpuCoolers");

                            b1.WithOwner()
                                .HasForeignKey("CpuCoolerId");
                        });

                    b.Navigation("RadiatorMaterial");
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuCoolerSocket", b =>
                {
                    b.HasOne("Components.Domain.Entities.CpuCooler", "CpuCooler")
                        .WithMany("CpuCoolerSockets")
                        .HasForeignKey("CpuCoolerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CpuCooler");
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuPowerConnector", b =>
                {
                    b.HasOne("Components.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany("CpuPowerConnectors")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motherboard");
                });

            modelBuilder.Entity("Components.Domain.Entities.Fan", b =>
                {
                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "BearingType", b1 =>
                        {
                            b1.Property<Guid>("FanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BearingType_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BearingType_Uk");

                            b1.HasKey("FanId");

                            b1.ToTable("Fans");

                            b1.WithOwner()
                                .HasForeignKey("FanId");
                        });

                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "Color", b1 =>
                        {
                            b1.Property<Guid>("FanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Color_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Color_Uk");

                            b1.HasKey("FanId");

                            b1.ToTable("Fans");

                            b1.WithOwner()
                                .HasForeignKey("FanId");
                        });

                    b.Navigation("BearingType");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Components.Domain.Entities.GpuPowerConnector", b =>
                {
                    b.HasOne("Components.Domain.Entities.Gpu", "Gpu")
                        .WithMany("GpuPowerConnectors")
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gpu");
                });

            modelBuilder.Entity("Components.Domain.Entities.InnerPort", b =>
                {
                    b.HasOne("Components.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany("InnerPorts")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motherboard");
                });

            modelBuilder.Entity("Components.Domain.Entities.M2Slot", b =>
                {
                    b.HasOne("Components.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany("M2Slots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motherboard");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCase", b =>
                {
                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "AdditionalFanPlaces", b1 =>
                        {
                            b1.Property<Guid>("PcCaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AdditionalFanPlaces_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AdditionalFanPlaces_Uk");

                            b1.HasKey("PcCaseId");

                            b1.ToTable("PcCases");

                            b1.WithOwner()
                                .HasForeignKey("PcCaseId");
                        });

                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "BuiltInFans", b1 =>
                        {
                            b1.Property<Guid>("PcCaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BuiltInFans_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BuiltInFans_Uk");

                            b1.HasKey("PcCaseId");

                            b1.ToTable("PcCases");

                            b1.WithOwner()
                                .HasForeignKey("PcCaseId");
                        });

                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "PsuLocation", b1 =>
                        {
                            b1.Property<Guid>("PcCaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PsuLocation_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PsuLocation_Uk");

                            b1.HasKey("PcCaseId");

                            b1.ToTable("PcCases");

                            b1.WithOwner()
                                .HasForeignKey("PcCaseId");
                        });

                    b.Navigation("AdditionalFanPlaces");

                    b.Navigation("BuiltInFans");

                    b.Navigation("PsuLocation");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCaseFanLocation", b =>
                {
                    b.HasOne("Components.Domain.Entities.PcCase", "PcCase")
                        .WithMany("PcCaseFanLocations")
                        .HasForeignKey("PcCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "Name", b1 =>
                        {
                            b1.Property<Guid>("PcCaseFanLocationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name_Uk");

                            b1.HasKey("PcCaseFanLocationId");

                            b1.ToTable("PcCaseFanLocations");

                            b1.WithOwner()
                                .HasForeignKey("PcCaseFanLocationId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PcCase");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCaseFormFactor", b =>
                {
                    b.HasOne("Components.Domain.Entities.PcCase", "PcCase")
                        .WithMany("PcCaseFormFactors")
                        .HasForeignKey("PcCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PcCase");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcleSlot", b =>
                {
                    b.HasOne("Components.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany("PcleSlots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motherboard");
                });

            modelBuilder.Entity("Components.Domain.Entities.PowerSupply", b =>
                {
                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "Modularity", b1 =>
                        {
                            b1.Property<Guid>("PowerSupplyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Modularity_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Modularity_Uk");

                            b1.HasKey("PowerSupplyId");

                            b1.ToTable("PowerSupplies");

                            b1.WithOwner()
                                .HasForeignKey("PowerSupplyId");
                        });

                    b.Navigation("Modularity");
                });

            modelBuilder.Entity("Components.Domain.Entities.PowerSupplyPowerConnector", b =>
                {
                    b.HasOne("Components.Domain.Entities.PowerSupply", "PowerSupply")
                        .WithMany("PowerSupplyPowerConnectors")
                        .HasForeignKey("PowerSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerSupply");
                });

            modelBuilder.Entity("Components.Domain.Entities.ProductOffer", b =>
                {
                    b.HasOne("Components.Domain.Entities.Store", "Store")
                        .WithMany("ProductOffers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Components.Domain.Entities.Ram", b =>
                {
                    b.OwnsOne("Components.Domain.ValueObjects.LocalizedString", "Color", b1 =>
                        {
                            b1.Property<Guid>("RamId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("En")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Color_En");

                            b1.Property<string>("Uk")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Color_Uk");

                            b1.HasKey("RamId");

                            b1.ToTable("Rams");

                            b1.WithOwner()
                                .HasForeignKey("RamId");
                        });

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Components.Domain.Entities.RearPort", b =>
                {
                    b.HasOne("Components.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany("RearPorts")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motherboard");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild", b =>
                {
                    b.HasOne("Components.Domain.Entities.CpuCooler", "CpuCooler")
                        .WithMany()
                        .HasForeignKey("CpuCoolerId");

                    b.HasOne("Components.Domain.Entities.ProductOffer", "CpuCoolerOffer")
                        .WithMany()
                        .HasForeignKey("CpuCoolerOfferId");

                    b.HasOne("Components.Domain.Entities.Cpu", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId");

                    b.HasOne("Components.Domain.Entities.ProductOffer", "CpuOffer")
                        .WithMany()
                        .HasForeignKey("CpuOfferId");

                    b.HasOne("Components.Domain.Entities.Gpu", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId");

                    b.HasOne("Components.Domain.Entities.ProductOffer", "GpuOffer")
                        .WithMany()
                        .HasForeignKey("GpuOfferId");

                    b.HasOne("Components.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId");

                    b.HasOne("Components.Domain.Entities.ProductOffer", "MotherboardOffer")
                        .WithMany()
                        .HasForeignKey("MotherboardOfferId");

                    b.HasOne("Components.Domain.Entities.PcCase", "PcCase")
                        .WithMany()
                        .HasForeignKey("PcCaseId");

                    b.HasOne("Components.Domain.Entities.ProductOffer", "PcCaseOffer")
                        .WithMany()
                        .HasForeignKey("PcCaseOfferId");

                    b.HasOne("Components.Domain.Entities.PowerSupply", "PowerSupply")
                        .WithMany()
                        .HasForeignKey("PowerSupplyId");

                    b.HasOne("Components.Domain.Entities.ProductOffer", "PowerSupplyOffer")
                        .WithMany()
                        .HasForeignKey("PowerSupplyOfferId");

                    b.HasOne("Auth.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");

                    b.Navigation("CpuCooler");

                    b.Navigation("CpuCoolerOffer");

                    b.Navigation("CpuOffer");

                    b.Navigation("Gpu");

                    b.Navigation("GpuOffer");

                    b.Navigation("Motherboard");

                    b.Navigation("MotherboardOffer");

                    b.Navigation("PcCase");

                    b.Navigation("PcCaseOffer");

                    b.Navigation("PowerSupply");

                    b.Navigation("PowerSupplyOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Fan", b =>
                {
                    b.HasOne("Components.Domain.Entities.Fan", "Fan")
                        .WithMany()
                        .HasForeignKey("FanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilds.Domain.Entities.PcBuild", "PcBuild")
                        .WithMany("PcBuild_Fans")
                        .HasForeignKey("PcBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Components.Domain.Entities.ProductOffer", "ProductOffer")
                        .WithMany()
                        .HasForeignKey("ProductOfferId");

                    b.Navigation("Fan");

                    b.Navigation("PcBuild");

                    b.Navigation("ProductOffer");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Hdd", b =>
                {
                    b.HasOne("Components.Domain.Entities.Hdd", "Hdd")
                        .WithMany()
                        .HasForeignKey("HddId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilds.Domain.Entities.PcBuild", "PcBuild")
                        .WithMany("PcBuild_Hdds")
                        .HasForeignKey("PcBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Components.Domain.Entities.ProductOffer", "ProductOffer")
                        .WithMany()
                        .HasForeignKey("ProductOfferId");

                    b.Navigation("Hdd");

                    b.Navigation("PcBuild");

                    b.Navigation("ProductOffer");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Ram", b =>
                {
                    b.HasOne("PcBuilds.Domain.Entities.PcBuild", "PcBuild")
                        .WithMany("PcBuild_Rams")
                        .HasForeignKey("PcBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Components.Domain.Entities.ProductOffer", "ProductOffer")
                        .WithMany()
                        .HasForeignKey("ProductOfferId");

                    b.HasOne("Components.Domain.Entities.Ram", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PcBuild");

                    b.Navigation("ProductOffer");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild_Ssd", b =>
                {
                    b.HasOne("PcBuilds.Domain.Entities.PcBuild", "PcBuild")
                        .WithMany("PcBuild_Ssds")
                        .HasForeignKey("PcBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Components.Domain.Entities.ProductOffer", "ProductOffer")
                        .WithMany()
                        .HasForeignKey("ProductOfferId");

                    b.HasOne("Components.Domain.Entities.Ssd", "Ssd")
                        .WithMany()
                        .HasForeignKey("SsdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PcBuild");

                    b.Navigation("ProductOffer");

                    b.Navigation("Ssd");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.Review", b =>
                {
                    b.HasOne("PcBuilds.Domain.Entities.PcBuild", "PcBuild")
                        .WithMany("Reviews")
                        .HasForeignKey("PcBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PcBuild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Components.Domain.Entities.CpuCooler", b =>
                {
                    b.Navigation("CpuCoolerSockets");
                });

            modelBuilder.Entity("Components.Domain.Entities.Gpu", b =>
                {
                    b.Navigation("GpuPowerConnectors");
                });

            modelBuilder.Entity("Components.Domain.Entities.Motherboard", b =>
                {
                    b.Navigation("CpuPowerConnectors");

                    b.Navigation("InnerPorts");

                    b.Navigation("M2Slots");

                    b.Navigation("PcleSlots");

                    b.Navigation("RearPorts");
                });

            modelBuilder.Entity("Components.Domain.Entities.PcCase", b =>
                {
                    b.Navigation("PcCaseFanLocations");

                    b.Navigation("PcCaseFormFactors");
                });

            modelBuilder.Entity("Components.Domain.Entities.PowerSupply", b =>
                {
                    b.Navigation("PowerSupplyPowerConnectors");
                });

            modelBuilder.Entity("Components.Domain.Entities.Store", b =>
                {
                    b.Navigation("ProductOffers");
                });

            modelBuilder.Entity("PcBuilds.Domain.Entities.PcBuild", b =>
                {
                    b.Navigation("PcBuild_Fans");

                    b.Navigation("PcBuild_Hdds");

                    b.Navigation("PcBuild_Rams");

                    b.Navigation("PcBuild_Ssds");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
