<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Moderation.Domain\Moderation.Domain.csproj" />
    <ProjectReference Include="..\..\..\PcBuilder.SharedKernel\PcBuilder.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Auth\Auth.Domain\Auth.Domain.csproj" />
    <ProjectReference Include="..\..\PcBuilds\PcBuilds.Domain\PcBuilds.Domain.csproj" />
    <ProjectReference Include="..\..\Components\Components.Domain\Components.Domain.csproj" />
    <ProjectReference Include="..\..\Auth\Auth.Application\Auth.Application.csproj" />
    <ProjectReference Include="..\..\Notifications\Notifications.Application\Notifications.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
